### ISSUE TITLE
Class "Google_Client" not found

### ISSUE THREAD

**Issue by iw-hotze** [dr-blitz-weblab/google_indexer#10]
When I try to update a page or confirm check status, I get the following error:
503
Oops, an error occurred!
Class "Google_Client" not found

I also find the following in the log:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class "Google_Client" not found | Error thrown in file /usr/www/users/gebaed/typo3cms11/typo3conf/ext/google_indexer/Classes/Service/GoogleIndexingApi.php in line 100. Requested URL: https://www.gebaeudereinigung-scheler.de/typo3/module/web/GoogleIndexerGoogleindexer?token=--AnonymizedToken--&id=387&tx_googleindexer_web_googleindexergoogleindexer%5Blanguage%5D=0&tx_googleindexer_web_googleindexergoogleindexer%5Baction%5D=checkStatus&tx_googleindexer_web_googleindexergoogleindexer%5Bcontroller%5D=Module

**Comment by drblitz-weblab** [comment]
Hello @iw-hotze  please install extension  ```composer req drblitz/google-indexer```
