### ISSUE TITLE
(1/1) ParseError syntax error, unexpected 'protected' (T_PROTECTED), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by CMS-Internetsolutions** [dr-blitz-weblab/google_indexer#8]
Dear Developer,
I am getting the following error message (see) screenshot.

TYPO3 11
![FireShot Pro Webpage Screenshot #016 - 'TYPO3 Exception'  site](https://github.com/dr-blitz-weblab/google_indexer/assets/107540699/76422ab0-8f66-483d-83a8-b824e8a364b1)

Composer installation

Thanks a lot

**Comment by drblitz-weblab** [comment]
Hello @CMS-Internetsolutions 

can you tell which PHP version you use ?

**Comment by maciejszklarczyk** [comment]
Fix is on it's way.

**Comment by drblitz-weblab** [comment]
Fixed by #9

**Comment by drblitz-weblab** [comment]
@CMS-Internetsolutions
